### ISSUE TITLE
Charts unter Contao 4

### ISSUE THREAD

**Issue by zonky2** [mathContao/be_piwikcharts#2]
Die Erweiterung läuft auch noch unter 4.4 :D

Leider werden die Bilder im BE von 400px auf 320px runter skaliert, so dass diese sehr krisselig ausshen - ggf. kann man das uch 400px anheben, d.h. den Skalierungsfaktor auf 100 setzen.

**Comment by mathContao** [comment]
Kannst du mir bitte ein Screenshot (wenn möglich mit dem zugehörigen HTML) zusenden?
Ich habe leider kein Contao 4.4

**Comment by zonky2** [comment]
aktuell: https://easycaptures.com/fs/uploaded/1403/6751412246.png

```
<img src="https://XXX/index.php?module=API&amp;method=ImageGraph.get&amp;idSite=1&amp;token_auth=1e5fb0f4eed01f614a9d740ed10917d2&amp;period=range&amp;date=previous30&amp;apiModule=DevicesDetection&amp;apiAction=getBrowsers&amp;graphType=horizontalBar&amp;width=400&amp;height=200" alt="" style="" width="320">
```

**Comment by mathContao** [comment]
OK, das muss ich mir genauer anschauen. 

Gründe für die aktuelle Skalierung:
Die Abbildungen mit einer Breite >400px sind qualitativ nicht so gut, da sie Text abschneidet.
Bei den alten Contao-Versionen (z.B. Contao 3.5 und älter) war jedoch kein Platz für 2 Abbildungen von 400px nebeneinander.

Das ist mit der neuen Contao-Version jetzt etwas anders.

**Comment by zonky2** [comment]
hmmm wann...

**Comment by mathContao** [comment]
Kannst du bitte mal schauen:

Datei ./bepiwikcharts.php (Zeilen 352, 353 und 437 bis 459)

Wenn die Funktion printChart() aufgerufen wird, dann wird ihr immer der Parameter $scale mit dem Wert 80 (also auf 80% skalieren) übergeben. Wenn du dort bei den betroffenen Zeilen die Zahl 100 eingibst, dann werden die Grafiken nicht mehr verkleinert.

Löst es das Problem?

**Comment by mathContao** [comment]
Mit 1.6 gelöst
